### ISSUE TITLE
Can't download manga at Mangakakalot

### ISSUE THREAD

**Issue by RedSquirrel87** [RedSquirrel87/manga-downloader#355]
**[Original report](https://bitbucket.org/Red_Squirrel/manga-downloader/issues/355) by Anonymous.**

----------------------------------------

Recent, I tried download this manga " Yankee JK KuzuHana-chan " in mangakakalot.com . But i can't download it. I check log and see this report: " [Fri Jun 26 16:30:45 ICT 2020] Program started.
[Fri Jun 26 16:32:06 ICT 2020] Loading manga from https://mangakakalot.com/manga/xg922613
[Fri Jun 26 16:32:07 ICT 2020] 14 chapters found. " 
Can you guide me fix it. Thanks.

![https://www.upsieutoc.com/images/2020/06/26/mangadownload.png" alt="mangadownload.png](https://www.upsieutoc.com/images/2020/06/26/mangadownload.png)

**Comment by alexia-beep** [comment]
HI first of all I would like to thank youuuu for this amazing project! you are a life saver @RedSquirrel87 

I am also facing this problem. Can you please look into it ? Thank you!!!!
