### ISSUE TITLE
Non acquisisce lista capitoli da mangadex

### ISSUE THREAD

**Issue by OrdinaryBes** [RedSquirrel87/manga-downloader#794]
Ciao, ho un problema quando provo a scaricare manga da Mangadex e ho visto che qualche mese fa anche un altro ragazzo aveva lo stesso problema. Uso windows coi dns di cloudflare, apro mangadex senza problemi col browser (uso firefox) ma anche aumentando il timeout di connessione non riesco a caricare la lista manga.

**Comment by RedSquirrel87** [comment]
Ciao, innanzitutto scusa se ti rispondo soltanto adesso ma non mi è arrivata la notifica di questo issue da github e quindi l'ho scoperto solo ora purtroppo. Riguardo il tuo problema dovresti allegare (o comunque controllare) il file jvm_log.txt, lì ti spiegherà nel dettaglio qual è il problema (se è qualcosa del genere "Connection refused" allora è un problema di DNS, prova a cambiarli o usare un altro PC). Da lato mio posso confermarti che ancora adesso (appena testato personalmente) il supporto a Mangadex sembra funzionare senza problemi, quindi non dovrebbe essere un bug generale
