### ISSUE TITLE
Reaperscans.com "Error while getting pages list!"

### ISSUE THREAD

**Issue by Steven-OConnell** [RedSquirrel87/manga-downloader#795]
It seems like something has changed _(yet again)_ on Reaperscans.com's backend.

Webtoon in question: https://reaperscans.com/comics/4073-overgeared

I've included the log however it isn't capturing the same error as the GUI, so here is what I'm getting on that end.

```
23:34:09:  Getting pages list for chapter Chapter 181 - Enemy of the 2nd place...
23:34:09:  Error while getting pages list!
```

[jvm_log.txt](https://github.com/RedSquirrel87/manga-downloader/files/11890496/jvm_log.txt)

**Comment by RedSquirrel87** [comment]
From what I can see in the log it's simply a http 429 error (too much requests, here more info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429 ). I will check this as soon as I will be at home but it should not be framework change or a bug, you should try to add more pause between requests (you can set this param in program's settings).

**Comment by RedSquirrel87** [comment]
Oh I just remembered about issue #768, there are probably so many chapters in that manga that the random wait between 1 and 2 seconds isn't even enough anymore. Or probably if you are unlucky you end up with too low waits all the time and so the website blocks them (in which case just try again and again until you are lucky enough to always catch the longest waits from the random values). I think that the only way to solve this problem without relying on random values anymore is to insert a new option in the program where the user himself can set the seconds of waits between requests only for this website, so that he can self-regulate them according to the manga and to how many chapters they have. I'll insert it in the next version 👍

**Comment by RedSquirrel87** [comment]
Ok I just tried and I can confirm that it's an issue related to the random waits values, after 3 failed attempts on the fourth it worked and loaded the list correctly. While waiting for the next release you should be able to fix this simply by trying and trying until it works

**Comment by RedSquirrel87** [comment]
I can confirm now that they have added the new option to the development version 👍 I have also added another extra option to set to load only chapters from the first page (useful when you want to get only the latest chapters released in chronological order without stressing the web site by loading unnecessarily the entire chapter list every time):
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/5c526b74-c6d1-43c3-97ad-9f1cda7604b3)
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/6851ec26-9f47-4929-9768-0282744d1c42)
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/0ff59343-bc7c-4a59-a364-05c30f282066)

This will be already available in tonight's nightly build and of course it will be included in the next public release too (ETA: next week if nothing goes wrong).

**Comment by Steven-OConnell** [comment]
Wow awesome, thanks so much. :)

**Comment by RedSquirrel87** [comment]
I just discovered that they introduced a new anti-bot challenge in the online viewer:
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/25d5edde-3fbc-4f1d-bd92-835cb92b8414)
Does it still work for you?

**Comment by Steven-OConnell** [comment]
Oh wow, I was unaware they were doing that.
It seems to be a global feature as I’m also seeing the same thing, I tried making an account to see if that would change anything but to no avail.

It seems like they REALLY don’t want people scraping their content.

**Comment by RedSquirrel87** [comment]
v62 just released, it should fix this issue
