### ISSUE TITLE
Custom Chapter Sorting (Suggestion)

### ISSUE THREAD

**Issue by Shamroc** [RedSquirrel87/manga-downloader#796]
I've noticed when downloading chapters as a single file and sorting them by date uploaded, I'll still get chapters out of order, and due to multiple scanlating teams taking on projects, naming schemes are inconsistent as well, my suggestion is being able to custom sort the order after bringing in the files to ensure that you can fine tune the chapter orders so they don't get messed up in single file downloads. I don't know if this is feasible, or if it already exists, if it does then I'm just not observant enough :/

**Comment by RedSquirrel87** [comment]
Nope, for now you can only reverse the order of how they appear on the source website. I will try to implement a manual sort function which indeed seems like a useful addition 👍

**Comment by RedSquirrel87** [comment]
v61 released, it adds the custom chapter sorting for the single file download mode

**Comment by Shamroc** [comment]
Helllllll yeah
