### ISSUE TITLE
Asura Scans domain change.

### ISSUE THREAD

**Issue by Steven-OConnell** [RedSquirrel87/manga-downloader#797]
Asura Scans has changed their domain from asurascans.com to [asura.gg](https://asura.gg/)

Forcing a generic framework of any kind will not get mitigate the issue.

**Comment by RedSquirrel87** [comment]
Thank you for reporting the issue, I'll try to fix this in the upcoming new version

**Comment by RedSquirrel87** [comment]
v61 released, it adds the support for the new domain asuracomics.com
