### ISSUE TITLE
Readcomiconline.li

### ISSUE THREAD

**Issue by CosmicKahos** [RedSquirrel87/manga-downloader#798]
>When you report an issue please be sure to:
>1. Include the URL of the manga and specify what its chapter gives the issue
>2. Paste/Upload the **jvm_log.txt** file! 
>You'll can find the jvm_log.txt file created automatically by the program in the same folder where the program's executable is.

Having some issue when trying to download from ReadComicOnline.li  It returns back with no chapters found.

URL: https://readcomiconline.li/Comic/Wolverine-Old-Man-Logan

Log:
[Sun Jul 23 13:48:39 CDT 2023] Program started.
[Sun Jul 23 13:48:39 CDT 2023] MangaDownloader v60.2
[Sun Jul 23 13:48:39 CDT 2023] OS: Windows 11 (amd64) | JVM: 11.0.17
[Sun Jul 23 13:48:40 CDT 2023] [DB] Database current version: 5
[Sun Jul 23 13:48:42 CDT 2023] Loading manga from https://readcomiconline.li/Comic/Wolverine-Old-Man-Logan
[Sun Jul 23 13:48:43 CDT 2023] HTTP response code: 200
[Sun Jul 23 13:48:43 CDT 2023] Framework: READCOMICONLINE
[Sun Jul 23 13:48:43 CDT 2023] 0 chapters found.
[Sun Jul 23 13:48:48 CDT 2023] Program closed.

**Comment by RedSquirrel87** [comment]
That's weird, I just tried and it worked without issues here for me:
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/601d3657-2395-4b15-9c84-0bbae398e366)

Is this the first title you're trying to download from ReadComicOnline? Does it work for you with other titles from the same source?

**Comment by CosmicKahos** [comment]
Yeah its my first time. Just tried the following comics and its still not loading any chapters. I can go to the site and read it there fine. 

https://readcomiconline.li/Comic/Earp-Saints-For-Sinners
https://readcomiconline.li/Comic/The-Dark-Side-of-the-Z

**Comment by CosmicKahos** [comment]
Downloaded a fresh install of the downloader and it works fine now. Not sure what the issue was.
