### ISSUE TITLE
Feature request - creating folders list without downloading any files

### ISSUE THREAD

**Issue by bumbaras** [RedSquirrel87/manga-downloader#801]
Sometimes i already have content aquired with different way, but the site has chapters with title names. It would be nice if MD would allow to only make empty downloads where the folders structure is created. Is it possible to add something like that?
Sometimes there are more sources where poor quality ones has good described chapters titles, and the good ones has only chapters numbers and nothing more. It is doable to make it step by step manually but I am pretty sure it would be easy to do this by MD.

**Comment by RedSquirrel87** [comment]
So you want the program to create folders with manga and chapter names without downloading anything inside them? Something like this:
```
- Folder with manga title
--Subfolder with title chapter 1 (empty folder)
--Subfolder with title chapter 2 (empty folder)
--Subfolder with title chapter 3 (empty folder)
```
etc...
Did I get it right?

**Comment by bumbaras** [comment]
Exactly what I had in mind. It wasn't the hypotetical urge but real case - I found two sources for some webtoon, one was poor quality but all chapters had title names beside number, and second with good quality but chapters were only numbered. It was over 80 chapters and I finally got what I wanted by interrupting all starting downloads (folder created, few images downloaded).

**Comment by RedSquirrel87** [comment]
v62 just released, it should fix this issue
