### ISSUE TITLE
Webtoon Line

### ISSUE THREAD

**Issue by bumbaras** [RedSquirrel87/manga-downloader#806]
Can You add webtoon line quality control switch? It can be controlled by attribute q90 (or other number) added to link. q90 is default for website, and q70 for mobile app. Your app downloads jpgs with 100% quality (very big). I think that any number above 90 is not working and not sure if numbers below 70 are working or not, but quality from 70 to 90 works good.

Can i somehow change bug to enhancement flag or any other flag creating post?

**Comment by RedSquirrel87** [comment]
Sure, no problem to add an extra setting for that website, I'll add it into next version 👍

**Comment by RedSquirrel87** [comment]
v62 just released, it should fix this issue
