### ISSUE TITLE
Madara Framework Saving Dupe Images

### ISSUE THREAD

**Issue by SpiralKipz** [RedSquirrel87/manga-downloader#807]
Edit: to clarify, this is when using the `Force a generic framework` option set to `Madara (WordPress Theme for Manga)`

When downloading chapters it saves each page twice (Page 1 as 001 and 002, Page 2 as 003 and 004, etc.). I didn't look for other sites of the same framework to test on that aren't supported by default so I don't know if it's true for others, but this happened when downloading from drakescans.com for me, and I tested it in two different series which both did the double downloads.

**Comment by RedSquirrel87** [comment]
Please could you provide the link of the manga you're trying to download? Thank you for reporting the issue

**Comment by SpiralKipz** [comment]
The two I experienced it on are these:
https://drakescans.com/series/after-ten-years-of-chopping-wood-immortals-begged-to-be-my-disciples171745/
https://drakescans.com/series/im-stuck-on-the-same-day-for-a-thousand-years/

**Comment by RedSquirrel87** [comment]
> The two I experienced it on are these: https://drakescans.com/series/after-ten-years-of-chopping-wood-immortals-begged-to-be-my-disciples171745/ https://drakescans.com/series/im-stuck-on-the-same-day-for-a-thousand-years/

Thank you, I'll see to fix this asap

**Comment by RedSquirrel87** [comment]
v62 just released, it should fix this issue
