### ISSUE TITLE
MangaPark No Longer Working After Website v5.2 Update

### ISSUE THREAD

**Issue by gokieks** [RedSquirrel87/manga-downloader#810]
https://mangapark.net was recently updated to v5.2, and that has broken the functionality in Manga Downloader.  The list of chapters will load correctly, but trying to download any of them results in an error while getting pages list.  Issue appears to be site-wide (not with any specific title).

JVM Log:

[Sun Dec 03 17:13:03 CST 2023] Program started.
[Sun Dec 03 17:13:03 CST 2023] MangaDownloader v61.4
[Sun Dec 03 17:13:03 CST 2023] OS: Mac OS X (x86_64) | JVM: 1.8.0_311
[Sun Dec 03 17:13:03 CST 2023] Patreon status: no linked Patreon account.
[Sun Dec 03 17:13:04 CST 2023] [DB] Database current version: 5
[Sun Dec 03 17:13:11 CST 2023] Loading manga from https://mangapark.net/title/223020-en-the-greatest-estate-designer
[Sun Dec 03 17:13:12 CST 2023] HTTP response code: 200
[Sun Dec 03 17:13:12 CST 2023] Framework: MANGAPARK
[Sun Dec 03 17:13:13 CST 2023] [MANGAPARK] Getting chapters data...
[Sun Dec 03 17:13:14 CST 2023] 121 chapters found.
[Sun Dec 03 17:13:16 CST 2023] Download started for chapter Chapter 116
[Sun Dec 03 17:13:17 CST 2023] Error: unable to find imageSet struct.

**Comment by RedSquirrel87** [comment]
Thank you for reporting the issue, I'll try to fix this in time for the planned pre-Christmas new release 👍

**Comment by RedSquirrel87** [comment]
v62 just released, it should fix this issue
