### ISSUE TITLE
Error downloading images from Bato it's mirrors.

### ISSUE THREAD

**Issue by Zavake** [RedSquirrel87/manga-downloader#815]
In v62, while trying to download chapter 1 (or any others) from https://battwo.com/series/119755/the-holy-power-of-modern-medicine-official, all I get is "Error while downloading image at URL". Same happens for every series I tried, in both BATOTOMIRROR and BATOTOV3XMIRROR.

17:04:58:  Getting pages list for chapter Chapter 1...
17:04:59:  99 pages found for this chapter.
17:04:59:  Downloading pages...
17:05:37:  Error while downloading image at URL  https://xfs-s124.batcg.org/comic/7006/00c/63e3f24307cb590e55579c00/24948380_940_1969_72670.webp?acc=NPi9RCJHYpF6sv-RC4M88Q&exp=1705334202
17:05:37:  Trying again...
17:08:07:  Error while downloading image at URL  https://xfs-s124.batcg.org/comic/7006/00c/63e3f24307cb590e55579c00/24948397_940_1979_57874.webp?acc=e83up8zdo6PO38ARgM9cLg&exp=1705334202
17:08:07:  Trying again...
etc

**Comment by RedSquirrel87** [comment]
Thank you for reporting the issue, does it happen only for this specific manga?

**Comment by Zavake** [comment]
No, I tried a couple others with same results.

**Comment by RedSquirrel87** [comment]
Ok I'll try to see if it can be fixed quickly and release a quick update

**Comment by RedSquirrel87** [comment]
I just tried with the same manga and it works for me here, could you share your jvm_log.txt content? It seems to be something on your side, maybe a configuration or network issue?

**Comment by RedSquirrel87** [comment]
However, I noticed that the download is very slow at the moment, there is probably some issue with their server itself. If in your log you have something like "connection timeout" or "read timeout" then that's exactly why

**Comment by Zavake** [comment]
Here you go, yeah looks like it's just timeouts.
[jvm_log.txt](https://github.com/RedSquirrel87/manga-downloader/files/13940756/jvm_log.txt)

**Comment by Zavake** [comment]
Looks like it was just the timeout issue, is working flawlessly now.
