### ISSUE TITLE
Problem with aine

### ISSUE THREAD

**Issue by forkirara** [RedSquirrel87/manga-downloader#816]
Hello.
I have a problem with Aineteam site. Sometimes doesn't download (in attach log). For example:
https://www.aineteam.it/manga/manga/caccia-allimperatrice
[jvm_log.txt](https://github.com/RedSquirrel87/manga-downloader/files/13986647/jvm_log.txt)
Can you help me, please?
Thanks

**Comment by RedSquirrel87** [comment]
From what I can see from the log it seems to be a issue related to SSL certificates used by the website, I'll try to search for info about this problem and see if it's fixable.
Thank you for reporting the issue

**Comment by RedSquirrel87** [comment]
Allora, te lo scrivo in Italiano che mi risulta più veloce (tanto il sito in questione fa solo manga in Italiano quindi immagino tu lo sappia). Ho trovato maggiori informazioni a riguardo, purtroppo non è un problema risolvibile da lato del programma ma devi importare manualmente nel tuo sistema il certificato SSL del sito web in questione. 
Sfortunatamente è una procedura un po' macchinosa e non proprio a prova di noob, io te la riporto come l'ho effettuata e testata, poi vedi tu se vuoi seguirla o meno.

1. Scarica il certificato dal sito:
Per farlo visita https://i.im.ge/2024/01/15/YoMg3T.00.jpg dal tuo browser (io uso Chrome nell'esempio), dopodiché una volta caricata la pagina clicca sull'iconcina affianco all'URL e scegli "La connessione è sicura": 
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/f6f82ca5-7aa7-4c14-ae5d-abed331fcab3)
Dopodiché sotto clicca su "Il certificato è valido":
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/24ead778-0de7-4a8b-a37b-ace95dd30884)
Così facendo ti apre un popup coi dati del certificato a centro pagina, clicca sulla linguetta "Dettagli":
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/6e23cda6-8461-474b-9d14-c4d34d798b32)
Nella nuova pagina clicca sul pulsante "Esporta":
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/4f117352-d06c-442d-9017-f3e31b8ff565)
A questo punto ti chiederà di scaricare un file (che è quello del certificato appunto), salvalo dove ti pare sul tuo PC (possibilmente nominandolo in modo facile e in una cartella facile da raggiungere visto che dopo dovrai scriverne il percorso a mano!).
Alla fine otterrai sul PC un file del genere:
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/ec4bb570-c522-4a2d-b46a-9dcba808f2c1)

2. Importa il certificato nel keystore di JAVA:
Per prima cosa devi trovare dove hai installato JAVA, nel mio PC (con Windows 10) è di default su C:\Programmi\JAVA ma se hai usato installatori personalizzati magari è diverso (oppure se usi altri sistemi operativi è diverso).
A questo punto all'interno della cartella trovi tutte le versioni di JAVA che hai installate:
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/69901e38-6735-4f57-b8a3-ef51efcbfa49)
Cerca quella che stai usando di default (per sapere qual è puoi dare il comando `java --version` nel terminale di Powershell e scoprire quale versione è), nel mio caso era jdk-21:
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/8cee1342-cec1-42ab-99c3-4288b3216b57)
Quindi entra nella cartella corrispondente alla versione che stai usando e troverai dentro delle cartelle, assicurati che ci sia quella "bin":
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/1746edb1-58e5-4d1c-b775-f78a346e7f57)
Ora dal menù start cerca la voce "Windows Powershell" e cliccandoci col destro scegli la voce "Esegui come amministratore" (ovviamente se stai usando Linux o Mac invece basta aprire il terminale e loggarsi come root):
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/5938a41e-2210-4300-a508-91cfe63f9b5c)
A questo punto in Powershell devi semplicemente scrivere questi comandi:
`cd "C:\Program Files\Java\jdk-21\bin"`
(ovviamente se il tuo percorso di installazione di JAVA è diverso devi modificare di conseguenza, in generale il comando è "cd percorsodiinstallazioneJava\versioneJava\bin" ricordandoti di inserire le virgolette " alle estremità del percorso in caso ci fossero spazi al suo interno!)
Una volta che sei nella cartella e te ne accorci perché la riga del terminale è cambiata nel nome della cartella, così:
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/5e2fad7b-8d26-45fe-893f-dca7b949e7ca)
A questo punto puoi dare il comando finale che sarà:
`.\keytool.exe -import -alias i.im.ge -keystore ../lib/security/cacerts -file "C:\Desktop\image.01.cdn.im.ge.crt"`
Ovviamente anche qui la parte relativa a -file devi cambiarla in base a dove hai salvato il file del certificato e su come l'hai nominato. Nel mio esempio il file l'ho chiamato image.01.cdn.im.ge.crt e l'avevo salvato sul desktop (per questo prima ti avvisavo di usare un nome e una cartella che siano facili da scrivere).
Se tutto è giusto e il programma trova l'eseguibile e il certificato ti verrà posta una domanda (se vuoi importare il certificato appunto) a cui devi rispondere (scrivendolo e dando poi INVIO) semplicemente yes:
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/26d08c5f-61ee-4e5f-8037-b1fd24b5369f)

Tutto qui, il certificato è ora importato e provando a scaricare ora il programma non ti darà più errore 👍

**Comment by forkirara** [comment]
Grazie, sei stato gentilissimo e chiarissimo. L'ho solo dovuto adattare a linux :)
