### ISSUE TITLE
https://manhuascan.com domain - blank screen shows up instead of chapter list 

### ISSUE THREAD

**Issue by alexia-beep** [RedSquirrel87/manga-downloader#817]
HI, i am sorry to bother  you again.  Basically the manhuascan.com domain is not working and a  blank screen shows up instead of chapter list . Thank you.

**Comment by RedSquirrel87** [comment]
Thank you for reporting the issue and sorry for the late reply but if you don't assign the issue to me when you create it then GitHub doesn't send me the notification 😅
It seems they changed the framework they use for the chapters list, I'll try to fix this for next version 👍

**Comment by alexia-beep** [comment]
Sorry I did not know I had to do that and how to assign it to you exactly.
Thank you for the reply I really appreciate your commitment!!!! thanks
alot!!!! looking forward to the next version!!!!
