### ISSUE TITLE
Bato.to is not working due to Error: unknown JSON data.

### ISSUE THREAD

**Issue by Pageandpencil** [RedSquirrel87/manga-downloader#818]
>When you report an issue please be sure to:
This error occurs on anything on bato.to, but the one I first encountered it on was Sakamoto Days, all chapters (https://bato.to/series/81145/sakamoto-days-official)
jvm log:
[Wed Jan 31 11:51:44 CST 2024] Program started.
[Wed Jan 31 11:51:44 CST 2024] MangaDownloader v62.1
[Wed Jan 31 11:51:44 CST 2024] OS: Windows 11 (amd64) | JVM: 1.8.0_391
[Wed Jan 31 11:51:45 CST 2024] Patreon status: no linked Patreon account.
[Wed Jan 31 11:51:46 CST 2024] [DB] Database current version: 5
[Wed Jan 31 11:51:55 CST 2024] Loading manga from https://bato.to/series/81145/sakamoto-days-official
[Wed Jan 31 11:51:56 CST 2024] HTTP response code: 200
[Wed Jan 31 11:51:56 CST 2024] Framework: BATOTO
[Wed Jan 31 11:51:58 CST 2024] 151 chapters found.
[Wed Jan 31 11:52:05 CST 2024] Download started for chapter Chapter 151
[Wed Jan 31 11:52:06 CST 2024] Error: unknown JSON data.
[Wed Jan 31 11:55:02 CST 2024] Download started for chapter Chapter 151
[Wed Jan 31 11:55:03 CST 2024] Error: unknown JSON data.
[Wed Jan 31 11:55:15 CST 2024] Download started for chapter Chapter 151
[Wed Jan 31 11:55:15 CST 2024] Error: unknown JSON data.

**Comment by Pageandpencil** [comment]
One additional thing I realized is that it does work on bato.to/title, but not bato.to/series.

**Comment by RedSquirrel87** [comment]
v63 just released, it should fix this issue
