### ISSUE TITLE
mangapill immediately runs into error

### ISSUE THREAD

**Issue by otherfutures** [RedSquirrel87/manga-downloader#819]
>When you report an issue please be sure to:
>1. Include the URL of the manga and specify what its chapter gives the issue
http://mangapill.com/manga/7405/minami-kun-no-koibito

>2. Paste/Upload the **jvm_log.txt** file! 
>You'll can find the jvm_log.txt file created automatically by the program in the same folder where the program's executable is.
MangaDownloader v62.1;
Database current version 5;
Response code -405 after loading manga from URL;
Framework: MANGAPILL;
Response code 403 for trying to download pages;
Error: server returned a Content-Lenght (sic) header <= 0

List of chapters is correctly shown & it correctly identifies the number of pages to be downloaded, but any attempt to start downloading immediately runs into error & nothing is downloaded.

**Comment by RedSquirrel87** [comment]
Thank you for reporting the issue, the 403 error suggests either that they are behind Cloudflare (or similar) antibot protection (which would be very bad) or that they have changed the server where the images reside and therefore it requires some specific header to enable the access to the files (which would be very trivial).
I'll let you know as soon as possible

**Comment by RedSquirrel87** [comment]
I can confirm you that it was the second case and the support has already been fixed in the nightly builds and so it will be fixed in next public release too 👍

**Comment by otherfutures** [comment]
Wonderful, thank you (& thanks for the quick reply)!
