### ISSUE TITLE
Mangaworld and manga adult cambio dominio

### ISSUE THREAD

**Issue by Misaki4** [RedSquirrel87/manga-downloader#820]
Mangaworld ha cambiato estensione in .ac, mentre Manga Adult l'ha cambiata in .net.

**Comment by RedSquirrel87** [comment]
Grazie per la segnalazione, vedo di aggiornarlo già nella nightly di stasera se riesco, ma comunque sarà sicuramente modificato nella prossima release pubblica 👍
P.s.: colgo l'occasione per ricordarvi che se siete sostenitori su Patreon potete già cambiare manualmente da voi i domini dei siti web supportati usando l'apposita funzione nel menù Modifica -> Domini se non volete attendere l'aggiornamento

**Comment by RedSquirrel87** [comment]
v63 just released, it should fix this issue
