### ISSUE TITLE
Download from Comic Walker is not working

### ISSUE THREAD

**Issue by MarcusVCP** [RedSquirrel87/manga-downloader#821]
Hi, Comic Walker changed the site and now is not possible download anything.
Next is what happens when I tried download a chapter
https://comic-walker.com/detail/KC_005219_S/episodes/KC_0052190000100011_E

[Thu Feb 22 07:56:31 GMT-03:00 2024] Program started.
[Thu Feb 22 07:56:31 GMT-03:00 2024] MangaDownloader v62.1
[Thu Feb 22 07:56:31 GMT-03:00 2024] OS: Windows 7 (x86) | JVM: 1.8.0_301
[Thu Feb 22 07:56:32 GMT-03:00 2024] Patreon status: no linked Patreon account.
[Thu Feb 22 07:56:34 GMT-03:00 2024] [DB] Database current version: 5
[Thu Feb 22 07:56:45 GMT-03:00 2024] Loading manga from https://comic-walker.com/detail/KC_005219_S/episodes/KC_0052190000100011_E
[Thu Feb 22 07:56:46 GMT-03:00 2024] HTTP response code: 200
[Thu Feb 22 07:56:46 GMT-03:00 2024] Framework: COMICWALKER
[Thu Feb 22 07:56:47 GMT-03:00 2024] Error while getting chapters list:
java.lang.NullPointerException
	at mainpackage.ComicWalker.GetChapters(ComicWalker.java:48)
	at mainpackage.NewJFrame.GetChaptersList(NewJFrame.java:9568)
	at mainpackage.NewJFrame.GetChaptersList(NewJFrame.java:9217)
	at mainpackage.NewJFrame.access$23100(NewJFrame.java:165)
	at mainpackage.NewJFrame$211.run(NewJFrame.java:9968)
	at java.lang.Thread.run(Unknown Source)
[Thu Feb 22 07:56:47 GMT-03:00 2024] Error: NULL chapters list.

**Comment by RedSquirrel87** [comment]
Thank you for reporting the issue, most likely they have changed their API system and therefore I will have to study how the new one works. It will take some time but I will try to fix it as soon as possible

**Comment by RedSquirrel87** [comment]
Sorry for the wait but I can now confirm that support for ComicWalker has been fixed in the nightly builds and it will therefore also be available again in the next public release

**Comment by RedSquirrel87** [comment]
v63 just released, it should fix this issue
