### ISSUE TITLE
Readcomiconline.li shows 0 in manga downloader !!

### ISSUE THREAD

**Issue by madara123pain** [RedSquirrel87/manga-downloader#822]
Hi,i have been trying to download comics from supported sites now for example , whenever open any comic url from :-(https://readcomiconline.li/Comic/ThunderBeast  ) in manga downloader it shows 0 chapters though website has many 
[jvm_log.txt](https://github.com/RedSquirrel87/manga-downloader/files/14437768/jvm_log.txt)
Please have a look at this issue !!

**Comment by RedSquirrel87** [comment]
I just tested with the same link and no issue here for me:
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/9b2df69f-8650-4fa0-80c7-20c68904badc)

Please try to remove the cookies.dat file from your main folder, maybe there is some cookie that are causing problems with this site

**Comment by madara123pain** [comment]
Yeah its working now ,thanks for solving the issue!!
