### ISSUE TITLE
ReaperScans Not Working

### ISSUE THREAD

**Issue by SpiralKipz** [RedSquirrel87/manga-downloader#825]
>When you report an issue please be sure to:
>1. Include the URL of the manga and specify what its chapter gives the issue
>2. Paste/Upload the **jvm_log.txt** file! 
>You'll can find the jvm_log.txt file created automatically by the program in the same folder where the program's executable is.

Trying to get this series: https://reaperscans.com/comics/4450-past-life-returner

Upon installing the Manga Downloader Assistant extension in Firefox and following the instructions (I think), I just get an endless "Getting available chapters list for the manga, please wait..." If I restart the program, it'll just resume that upon entering the link without letting me re-enter an auth code. Maybe I'm just missing where you need to go to attempt to re-enter a separate auth code for another attempt, but it seems I just can't do anything with Reaper series now. I tested with another site and confirmed I can at least load series still, so it's not just that the app as a whole isn't working.

JVM from testing:

[Thu Apr 18 11:01:45 PDT 2024] Program started.
[Thu Apr 18 11:01:45 PDT 2024] MangaDownloader v62.1
[Thu Apr 18 11:01:45 PDT 2024] OS: Windows 10 (amd64) | JVM: 1.8.0_411
[Thu Apr 18 11:01:45 PDT 2024] Patreon status: no linked Patreon account.
[Thu Apr 18 11:01:59 PDT 2024] [DB] Database current version: 5
[Thu Apr 18 11:02:07 PDT 2024] Loading manga from https://reaperscans.com/comics/4450-past-life-returner
[Thu Apr 18 11:02:08 PDT 2024] HTTP response code: 200
[Thu Apr 18 11:02:08 PDT 2024] Framework: REAPERSCANS
Exception in thread "Thread-10" java.lang.NoSuchMethodError: java.util.Random.nextInt(II)I
	at mainpackage.ReaperScans.GetLivewireData(ReaperScans.java:92)
	at mainpackage.ReaperScans.GetChapters(ReaperScans.java:153)
	at mainpackage.NewJFrame.GetChaptersList(NewJFrame.java:9568)
	at mainpackage.NewJFrame.GetChaptersList(NewJFrame.java:9217)
	at mainpackage.NewJFrame.access$23100(NewJFrame.java:165)
	at mainpackage.NewJFrame$211.run(NewJFrame.java:9968)
	at java.lang.Thread.run(Unknown Source)

**Comment by RedSquirrel87** [comment]
That's because you're using the JRE and not the JDK in your OS, you can download and install JDK from here: https://www.oracle.com/java/technologies/downloads/#jdk22-windows (it's totally free of charge).
Also you don't need to uninstall JRE because JDK and JRE can coexist in the OS without any isse, but please remember to reboot your PC after the installation of JDK because it is required to proper set environment variables on Windows 👍

**Comment by SpiralKipz** [comment]
Ah, thanks! I had uninstalled Java because I didn't realize this app used it and then simply re-installed through the link that I think the app told me it needed to run lol. Guess it was the wrong thing.
