### ISSUE TITLE
Cambio dominio Mangaworld

### ISSUE THREAD

**Issue by SimonLollamen** [RedSquirrel87/manga-downloader#826]
Ciao, il dominio di mangaworld è cambiato in https://www.mangaworld.ac/, potresti modificare o aggiungerlo alla lista dei siti raggiungibili? Attualmente punta al vecchio dominio bz

**Comment by RedSquirrel87** [comment]
Si il dominio è già stato aggiornato nelle nightly build da tempo, se riesco a risolvere gli ultimi bug segnalati ho intenzione di rilasciare la nuova versione pubblica entro questo weekend 👍

**Comment by RedSquirrel87** [comment]
v63 just released, it should fix this issue
