### ISSUE TITLE
Bato.to not working on v62.1, even using v3

### ISSUE THREAD

**Issue by HikariGo** [RedSquirrel87/manga-downloader#827]
I understand that Bato.to is not working on the current working version (only fixed in nightly), but using the recommended Bato.to v3 is also not working for any titles with all downloads stuck indefinitely at 1% and producing the following error in log:

15:15:36:  Getting pages list for chapter Chapter 1...
15:15:39:  23 pages found for this chapter.
15:15:39:  Downloading pages...
15:15:39:  An unknown error occurred while downloading the chapter!
15:15:39:  The program returned the following description for the error: null
15:15:39:  Trying again…

Interested to know if there is a solution for this.

Cheers,
HikariGo

**Comment by RedSquirrel87** [comment]
v63 just released, it should fix this issue
