### ISSUE TITLE
MangaPark downloading manga cover and another image into each chapter

### ISSUE THREAD

**Issue by bwalker22** [RedSquirrel87/manga-downloader#828]
Mangapark downloads the cover chapter twice and might sometimes download another image to each chapter. 
https://mangapark.net/title/391380-en-primal-hunter gives 3 extra images at the start of each chapter.
![3](https://github.com/RedSquirrel87/manga-downloader/assets/61926475/da060b2b-23ac-4fe5-bfcb-e7dfb8056e33)

https://mangapark.net/title/107787-en-kaiju-no-8 gives 2 extra images.
![2](https://github.com/RedSquirrel87/manga-downloader/assets/61926475/9c045440-1269-47d2-a1ba-c171d2f641d3)

They're not in the chapters itself. I don't know if its intended or not. How do i stop it from downloading those extra pages and how do i stop it from downloading it as .jgp.jgp?

**Comment by bwalker22** [comment]
I cleared the stored preferences and it fixed my .jpg.jpg problem. i just have problems with it downloading the manga cover twice along with a random image sometimes

**Comment by RedSquirrel87** [comment]
It's not intended but there is no way to avoid it at the moment, as reported in the changelog of the latest version:
![Screenshot_2024-04-23-09-17-29-54_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/9159ad87-ce0d-4f29-92fd-ce8a39cce69a)

**Comment by bwalker22** [comment]
Thanks

**Comment by RedSquirrel87** [comment]
v64 released, it should fix this issue
