### ISSUE TITLE
Comick.app site url changed

### ISSUE THREAD

**Issue by CosmicKahos** [RedSquirrel87/manga-downloader#830]
https://Comick.app/ url changed to https://comick.io/
![Screenshot_20-5-2024_141131_comick cc](https://github.com/RedSquirrel87/manga-downloader/assets/140344965/297384b3-d092-49e3-9a85-51a0fafb011f)
![Screenshot_20-5-2024_141155_comick io](https://github.com/RedSquirrel87/manga-downloader/assets/140344965/a288b6b9-49f6-4fab-be6b-5aeacb3f2a29)

**Comment by RedSquirrel87** [comment]
Thank you for reporting the issue, I'll update the domain for this website in the next version

**Comment by RedSquirrel87** [comment]
I can confirm that this issue has now been resolved in the nightly builds and will therefore be fixed also in the next public release 👍

**Comment by RedSquirrel87** [comment]
v64 released, it should fix this issue
