### ISSUE TITLE
cant download from Hyperdex

### ISSUE THREAD

**Issue by adrianoaxl1** [RedSquirrel87/manga-downloader#834]
>1.https://hiperdex.top/manga/chicken-club/
>2. 
[jvm_log.txt](https://github.com/user-attachments/files/15753761/jvm_log.txt)

they changed the hyperdex.com to hyperdex.top so the program cant download.
thanks and have a good day

**Comment by RedSquirrel87** [comment]
Thank you for the reporting the issue, I will update the domain of the website in the next release 👍 
In the meantime, if you are a supporter of the program on Patreon, you can already change the domain of all supported websites by yourself using the dedicated feature you can find in the Edit -> Domains menu and get it working again straight away

**Comment by RedSquirrel87** [comment]
v64 released, it should fix this issue

**Comment by adrianoaxl1** [comment]
Hello again sorry for the trouble it's just to let you know that the hyperdex use the (. Com) again like they and now it's blocked cloudflare, I hope you have a amazing weekend and again sorry for the trouble Em 14/08/2024 20:11, Red Squirrel ***@***.***> escreveu:
v64 released, it should fix this issue
