### ISSUE TITLE
Downloads marked as failed even though it went successfully

### ISSUE THREAD

**Issue by Decondelite** [RedSquirrel87/manga-downloader#838]
>When you report an issue please be sure to:
>1. Include the URL of the manga and specify what its chapter gives the issue
>2. Paste/Upload the **jvm_log.txt** file! 
>You'll can find the jvm_log.txt file created automatically by the program in the same folder where the program's executable is.

While trying to download this manga:
https://mangapark.net/title/75290-en-yofukashi-no-uta

I get this error log in the status:
> 17:00:40:  Getting pages list for chapter Vol.0 Ch.200: Final Night: And Then...
17:00:41:  26 pages found for this chapter.
17:00:41:  Downloading pages...
17:00:42:  Error while downloading image at URL  https
17:00:42:  Trying again...
17:00:43:  Error while downloading image at URL  https
17:00:43:  Trying again...
17:00:44:  Error while downloading image at URL  https
17:00:44:  Trying again...
17:00:45:  Error while downloading image at URL  https
17:00:45:  Max retry attempts exceeded, image skipped.
17:00:46:  Error! Unable to detect the extension for the image file download at: https://mangapark.net/title/75290-en-yofukashi-no-uta/8400305-vol-0-ch-200
17:00:46:  Usually this mean that the server returned HTML code instead of the image file or simply the image is corrupted.
17:01:20:  Chapter downloaded.

jvm_log that comes with it:
[jvm_log.txt](https://github.com/user-attachments/files/16601530/jvm_log.txt)

In case of, my settings: default download parameters, downloading as CBZ.

And yet I do get my CBZ files just fine and I can read them in my manga reader program just fine.

**Comment by RedSquirrel87** [comment]
Yes, it's a known bug of the Mangapark framework current support (more info at #837 ) but don't worry, it will be fixed in the upcoming new version 👍

**Comment by Decondelite** [comment]
Well I saw that issue posted, but the error didn't look the same, so I wondered if it were an actual different issue.
It doesn't hurt to report it.

**Comment by RedSquirrel87** [comment]
Don’t worry, reporting an error is never wrong; in fact, it’s often the only way for me to notice a problem (since I don’t use the application often and, when I do, obviously I don’t use all the supported websites xD). So never apologize for reporting an error here, reports are always welcome 👍

**Comment by RedSquirrel87** [comment]
v64 released, it should fix this issue
