### ISSUE TITLE
templescan.net doesn't work

### ISSUE THREAD

**Issue by mollydeep** [RedSquirrel87/manga-downloader#842]
Hi. I'm sorry but templescan doesn't work.
Error is:
[Tue Aug 20 23:08:47 CEST 2024] Loading manga from https://templescan.net/comic/childhood-friend-complex
[Tue Aug 20 23:09:00 CEST 2024] HTTP response code: 200
[Tue Aug 20 23:09:00 CEST 2024] Framework: TEMPLESCAN
[Tue Aug 20 23:09:00 CEST 2024] Error: NULL chapters list.

I tried with multiple projects (not only childhood-friend-complex).
[jvm_log.txt](https://github.com/user-attachments/files/16682041/jvm_log.txt)

Can you help me, please? Site works (i can read everything). 
Thanks

**Comment by RedSquirrel87** [comment]
Well that's nornmal, support for Templescan has not been added to the program yet 😅 
As I mentioned in #64 , I was waiting for them to resolve their server issues before working on it.

**Comment by mollydeep** [comment]
Thanks

**Comment by RedSquirrel87** [comment]
v64.3 released, it should fix this issue 👍
