### ISSUE TITLE
Coffeemanga.io not working

### ISSUE THREAD

**Issue by faynore** [RedSquirrel87/manga-downloader#843]
coffeemanga.io
I try to download from thise website, it recognise the chapter but there are error when arrive to 100%
[jvm_log.txt](https://github.com/user-attachments/files/16730618/jvm_log.txt)

**Comment by RedSquirrel87** [comment]
It seems there is an error in the HTML code of their website, after a quick check I noticed that the IMG tags (from the third page of the chapter onwards) for some absurd reason have two "src" fields, which understandably messes up the HTML code interpretation 😅
![image](https://github.com/user-attachments/assets/48b96135-d1e3-4807-9b05-7b9132218031)
I’ll see if I can insert a temporary fix in the interpreter to make it read the first src field in case there are two

**Comment by RedSquirrel87** [comment]
v64.3 released, it should fix this issue 👍
