### ISSUE TITLE
comic-walker not working

### ISSUE THREAD

**Issue by AlanCampos10** [RedSquirrel87/manga-downloader#848]
Tried to download some mangas from Comic walker but it can't seem to load the chapters.

URL:
https://comic-walker.com/detail/KC_005368_S/episodes/KC_0053680000200011_E
https://comic-walker.com/detail/KC_005368_S/episodes/KC_0053680000200011_E?episodeType=first

Log:
[jvm_log.txt](https://github.com/user-attachments/files/16786082/jvm_log.txt)

screenshot
![a1](https://github.com/user-attachments/assets/e4724bda-f41a-494c-ae22-8325f6ac963e)

**Comment by RedSquirrel87** [comment]
Hmm, 403 http error usually means the server understood the request but refused to process it. So they now cana detect that you are using a program to access the site and block its access. I need to see if it is possible to bypass the detection

**Comment by RedSquirrel87** [comment]
I just released the v64.5 that should fix this issue 👍
