### ISSUE TITLE
Download new chapters will download every chapter

### ISSUE THREAD

**Issue by Enaella** [RedSquirrel87/manga-downloader#851]
Hey, I know you will hate me but here is another issue I found.
When you to to view > bookmark, and let's say you have a few that have new chapters
![image](https://github.com/user-attachments/assets/d89f0af7-8e73-4136-b4c7-34e8ba6c331f)

Technically, when you click on "download new chapters" it should download those new found chapters.  However it does not. for the webtoons ones I saw, it download every single chapters even those already downloaded. For the bato one, none. 
I checked my log file and... way too long of a copy so here is the file 
[jvm_log.txt](https://github.com/user-attachments/files/16829505/jvm_log.txt)

**Comment by RedSquirrel87** [comment]
Don’t worry, never apologize for reporting an error because your contribution is important for identifying issues since I don’t use the program often, and obviously, when I do, I don’t test every single supported site each time. 
Regarding the problem, I’ll check it right away and try to identify the issue and release an update. Surely there must have been some changes in the latest releases that broke something

**Comment by Enaella** [comment]
Thank you, I truly love your software/app/program, been using it for years. I understand that, just that it's twice within a few days that I report an issue ^^0 . (I noticed the scanning of new chapters from bookmarks is slower than before but I guess it's because it's searching webtoons et those seems to be a pain).

Thanks a lot!

**Comment by RedSquirrel87** [comment]
v64.7 released, it should fix this issue 👍

**Comment by RedSquirrel87** [comment]
> (I noticed the scanning of new chapters from bookmarks is slower than before but I guess it's because it's searching webtoons et those seems to be a pain).

In the Extra -> Webtoons menu there is an option to scan only the first page of the chapters list on the website, If you enable it the search should go faster (since it only download the first page of the chapters list).
