### ISSUE TITLE
Tappytoon download only 39 pages

### ISSUE THREAD

**Issue by mollydeep** [RedSquirrel87/manga-downloader#852]
Unfortunately tappytoon only downloads 39 pages even setting the cookie from your plugin.
Is it possible to correct?
Thanks

[jvm_log.txt](https://github.com/user-attachments/files/16873583/jvm_log.txt)

**Comment by RedSquirrel87** [comment]
Could you please try with the addon on Firefox? Unfortunately, since Google forced the upgrade to manifest v3, the extension on Chrome can no longer obtain all the cookies due to the new limitations imposed. Please try deleting the cookie.dat file and importing the cookies with Firefox addon, as the 403 error (access denied) might be due to that

**Comment by RedSquirrel87** [comment]
Even though, thinking about it, if it were a cookie problem, it shouldn’t download any at all and not stop after 39. The fact that you get a 403 access denied error makes me fear two things: either the site blocks access after a certain number of requests, or you take too long to download (have you set very long pauses?) and the keys for accessing the subsequent pages links end up expiring

**Comment by RedSquirrel87** [comment]
> Even though, thinking about it, if it were a cookie problem, it shouldn’t download any at all and not stop after 39. The fact that you get a 403 access denied error makes me fear two things: either the site blocks access after a certain number of requests, or you take too long to download (have you set very long pauses?) and the keys for accessing the subsequent pages links end up expiring

It seems to be the second, I just tested and checked the "expire" param of the pages links, it's set by the server to about 2 minutes after the moment the program get the pages links

**Comment by RedSquirrel87** [comment]
Please try to set the "Pausa tra il download delle pagine in secondi" to the minimal value you can, with 1 second for example you should be able to download about 100 pages before expiration and it should be enough for any chapter

**Comment by mollydeep** [comment]
Thank you very much!!! It is working :)
