### ISSUE TITLE
Webtoons issue

### ISSUE THREAD

**Issue by mollydeep** [RedSquirrel87/manga-downloader#855]
Ciao.
Scusa ma per alcuni progetti il programma mi crea dei nomi di cartelle con l'aggiunta di altri nomi.
Per esempio: 
https://www.webtoons.com/en/fantasy/the-age-of-arrogance/list?title_no=5839 
Il nome della cartella dovrebbe essere  The Age of Arrogance
invece la cartella creata è: The Age of Arrogance The Dragon King’s Bride Not Y
Aggiunge nomi di altri progetti.
Mi capita anche con altri, tipo:
https://www.webtoons.com/en/romance/when-the-mad-emperor-holds-me/list?title_no=6741
https://www.webtoons.com/en/romance/even-when-im-dead/list?title_no=6821
ecc...
Ma non succede con tutti...
[jvm_log.txt](https://github.com/user-attachments/files/17261213/jvm_log.txt)

**Comment by RedSquirrel87** [comment]
Probabilmente c'è qualche errore nei tag html che fanno trasbordare il riconoscimento del titolo in qualche altro sottotitolo pubblicitario di altri manga, grazie per aver segnalato il problema, vedo di risolverlo nella prossima versione 👍

**Comment by RedSquirrel87** [comment]
Posso confermare che questo problema è stato ora risolto nelle nightly build e sarà quindi risolto anche nella prossima release pubblica 👍

**Comment by RedSquirrel87** [comment]
v70 just released, it should fix this issue 👍
