### ISSUE TITLE
Templescan ha cambiato indirizzo

### ISSUE THREAD

**Issue by mollydeep** [RedSquirrel87/manga-downloader#856]
Vorrei segnalare che templescan ha cambiato indirizzo in:
https://templetoons.com/

**Comment by mollydeep** [comment]
Also after domain changed, doesn't work. Can you help me, please? I tried to set cookies from firefox, also.
Thanks
[jvm_log.txt](https://github.com/user-attachments/files/17338205/jvm_log.txt)

**Comment by RedSquirrel87** [comment]
Controllo subito

**Comment by RedSquirrel87** [comment]
A leggere dal tuo log sembra tu abbia modificato il dominio di Batoto per mettere quello di templetoons nuovo, o almeno da quanto vedo lui tenta di usare il framework BATOTOV3X:
![image](https://github.com/user-attachments/assets/7099f698-9929-4222-a4bc-256465383fb6)

Quando modifichi un dominio con l'apposita funzione devi sempre fare attenzione a modificare il vecchio dominio, poiché il framework che userà nel nuovo dominio lo prende appunto dal vecchio:
![image](https://github.com/user-attachments/assets/2acd5575-44ad-4ef1-ab5a-c94457d8f9e3)

Ho appena testato la procedura come da screenshot sopra e testando con uno a caso ([](https://templetoons.com/comic/the-name-of-emotions)) ti confermo che funziona senza problemi, quindi il framework non è cambiato ma solo il dominio 👍
![image](https://github.com/user-attachments/assets/16b0cb4d-264a-4bde-9f50-57eedcb68552)

**Comment by RedSquirrel87** [comment]
Ovviamente ricordati anche di ripristinare il vecchio dominio di batoto che hai modificato per errore, altrimenti userà sempre quello per templetoons ora

**Comment by mollydeep** [comment]
> Ovviamente ricordati anche di ripristinare il vecchio dominio di batoto che hai modificato per errore, altrimenti userà sempre quello per templetoons ora

In che senso? Non mi sembra di aver toccato bato.to. Però ho chiuso il programma e riaperto e ha funzionato. Dove vedi che ho cambiato il dominio di bato.to?

**Comment by RedSquirrel87** [comment]
Aspetta, ma tu quindi non avevi modificato il dominio con la procedura descritta sopra?
