### ISSUE TITLE
Possibilità di scaricare capitoli mancanti solo dei manga selezionati

### ISSUE THREAD

**Issue by golgoth85** [RedSquirrel87/manga-downloader#857]
Ho una lista dei preferiti piuttosto corposa: quando aggiungo nuovi manga e clicco su "scarica capitoli mancanti" (per scaricare il contenuto di quelli appena aggiunti) il programma va in tilt, nel senso che - dovendo riscaricare la lista di ogni capitolo di TUTTI i preferiti - il carico della CPU sale al massimo e manga downloader si blocca.
Non è possibile aggiungere una opzione (magari nel menù a tendina che si apre col tasto destro) per scaricare i capitoli mancanti solo dei manga selezionati?

**Comment by RedSquirrel87** [comment]
Ciao, innanzitutto scusa se ti rispondo dopo 5 giorni ma ho notato solo adesso il messaggio (in futuro ricordati di assegnare l'issue a me tramite l'apposito tastino qui nel menù a destra, altrimenti non mi arriva la notifica di Github e finisce che non leggo subito 👍 ). 
Per quanto riguarda la tua domanda in sé, questa opzione esiste già nel programma, infatti nella schermata dei preferiti c'è la possibilità di selezionare manualmente i capitoli della lista e cliccando col destro su di essi poi compare il menu dove puoi scegliere di controllare i capitoli mancanti solo di quelli selezionati:
![image](https://github.com/user-attachments/assets/ab2e710b-b97d-4542-ac80-76533fb3caec)

P.s.: ti ricordo in caso non lo sapessi che per selezionare elementi della lista non consecutivi tra loro basta tenere premuto CTRL sulla tastiera e cliccarci sopra col mouse 👍
