### ISSUE TITLE
Problema cambio dominio

### ISSUE THREAD

**Issue by mollydeep** [RedSquirrel87/manga-downloader#861]
Avrei un problema.
Ogni volta che cambio il dominio di templescan (ora templetoons) il programma non prende il framework templescan ma quello dell'ultimo file scaricato (prima era webtoons, poi ho provato a cambiare con batoto).
[jvm_log.txt](https://github.com/user-attachments/files/17459116/jvm_log.txt)
Se chiudo il programma e lo riapro, funziona.
[jvm_log.txt](https://github.com/user-attachments/files/17459861/jvm_log.txt)
Sbaglio qualcosa io?
Grazie

**Comment by RedSquirrel87** [comment]
Per essere chiari, cambiando il dominio seguendo la procedura che ti ho illustrato in #856 poi non ti prende correttamente il nuovo dominio fino al riavvio del programma, giusto? Ma dopo il riavvio invece funziona sempre o ti torna a fare questo problema?

**Comment by RedSquirrel87** [comment]
Ok sono riuscito a riprodurre il problema, in pratica dopo aver cambiato il dominio se si cambia l'input con una altro sito poi non viene più ripristinato correttamente quello modificato fino ad un riavvio. Ora vedo di fixare il problema, grazie per la segnalazione 👍

**Comment by mollydeep** [comment]
Grazie a te :)

**Comment by RedSquirrel87** [comment]
v70 just released, it should fix this issue 👍
