### ISSUE TITLE
Powermanga

### ISSUE THREAD

**Issue by malligri** [RedSquirrel87/manga-downloader#866]
sembra che powermanga (https://powermangaforum.forumcommunity.net/) non stia più aggiungendo i propri capitoli su https://www.mangaworld.ac/
per esempio gli ultimi capitoli di Kagurabachi e Centuria non sono presenti:
si può aggiungere la possibilità di scaricare i capitoli direttamente da powermanga?
Grazie mille

**Comment by malligri** [comment]
si, praticamente una volta che entri da loggato in una delle varie sezioni divise per manga, trovi i link al loro reader che però sembra esterno, per l'esattezza su imgur.com

Ti lascio qualche esempio:
Kagurabachi 58
[https://imgur.com/a/kagurabachi-58-by-powermanga-forum-https-powermanga-forumcommunity-net-riunione-jWgl0XB
](https://imgur.com/a/kagurabachi-58-by-powermanga-forum-https-powermanga-forumcommunity-net-riunione-jWgl0XB
)
Centuria 31
[https://imgur.com/a/centuria-31-by-powermanga-forum-https-powermanga-forumcommunity-net-lukas-ylfbRl6](https://imgur.com/a/centuria-31-by-powermanga-forum-https-powermanga-forumcommunity-net-lukas-ylfbRl6)

Per esempio, per scaricarmi gli ultimi di Centuria, ho sfruttato [questo strumento](https://dschep.github.io/imgur-album-downloader/#/) inserendo l'album ID dei capitoli

**Comment by RedSquirrel87** [comment]
Il problema è che servirebbe una pagina del manga con l'elenco dei capitoli da cui attingere, sennò manca proprio il materiale da poter leggere purtroppo. In pratica Manga Downloader funziona essenzialmente così: dai come input un manga -> acquisisce la pagina con la lista capitoli -> la analizza e ne estrae automaticamente i link ai singoli capitoli -> si collega alla pagina estratta e ne scarica le immagini. Con powermanga manca del tutto il primo passaggio, non essendo un reader vero e proprio (con le raccolte di immagini presenti all'interno di post sparsi per un forum) manca il primo passo per il programma che fa purtroppo decadere l'intera catena successiva. Una volta ottenuto il link alla raccolta di imgur non ci sarebbe problema a scaricare le immagini, anzi è perfino più facile che rispetto a siti proprietari (imgur infatti ha delle API che facilitano un sacco le cose) ma resta il problema che non c'è modo sistematico di poter accedere alla lista di questi capitoli se non andando manualmente a prenderli all'interno di discussioni su un forum 😔

**Comment by malligri** [comment]
okok chiaro, ma ti chiedo, se inserendo l'url del manga (qui forse c'è già il primo problema perche devi essere loggato forumcommunity) si arriva in una pagina come quella che ti allego, con la lista di tutti gli imgur?
![Immagine 2024-11-27 173643](https://github.com/user-attachments/assets/69a3461c-0391-412f-9647-5c756c0a0e4c)

**Comment by RedSquirrel87** [comment]
Si ad occhio una pagina del genere andrebbe bene, me la puoi linkare così controllo a livello di sorgenti HTML se è fattibile?

**Comment by RedSquirrel87** [comment]
Come non detto, ho notato solo ora che si vede l'URL sopra xD
Solo che non mi fa accedere perché è protetta dietro login, ora provo a iscrivermi per vedere se non usano captcha (che sarebbero impossibili da aggirare per il programma)

**Comment by RedSquirrel87** [comment]
Ok mi sono iscritto ma andando all'URL ottengo questo messaggio di errore che non spiega assolutamente nulla di cosa stia sbagliando 😅 C'è altro da fare per vedere quella pagina oltre al login?
![image](https://github.com/user-attachments/assets/e394cfa3-c4a7-4450-a619-429be3ba3896)

**Comment by malligri** [comment]
allora, come utente, per poter vedere le sezioni manga, devi votarli in top qui
https://powermangaforum.forumcommunity.net/?t=60499974#entry429900978

**Comment by malligri** [comment]
fatto questo, dovresti atterrare sulla lista capitoli

**Comment by RedSquirrel87** [comment]
Perfetto, grazie 👍 Si, sembra fattibile come supporto così, certo estremamente fragile (basterebbe che postino altra roba nel messaggio sul forum per rompere totalmente il supporto immagino) e richiederebbe di inserire per forza un metodo per un login valido dell'utente (il programma da solo potrebbe anche loggarsi con account fasullo ma poi sta roba del votare ovviamente non potrebbe farla e rimarrebbe chiuso fuori quindi anche da loggato). Vedo di mettere il supporto nella prossima versione

**Comment by malligri** [comment]
grandissimo! eh purtroppo loro contribuivano a parecchi manga su mangaworld, quindi se si fermano si rischia di "perdere" un sacco di materiale..intanto grazie ancora per il supporto!! <3

**Comment by RedSquirrel87** [comment]
v70 rilasciata, aggiunto il supporto a powermanga come promesso 👍
