### ISSUE TITLE
Batoto - Error for all chapters, with Manga Downloader Assitant

### ISSUE THREAD

**Issue by KassAndrose** [RedSquirrel87/manga-downloader#871]
Hi RedSquirrel87,

I hope you are well and Happy Winter Holidays. :)

I am unable to download any of the chapters for Toxin from Bato.to
I have tried: 

1. Firefox & Chrome
2. I used the Manga Downloader Assistant in both.
3. I forced the Anti-Bot Protection, and tried again copy/pasting from the Manga Downloader Assistant. 
4. I tried several different Batoto URLs:

> https://xbato.net/series/159888/toxin-official
> https://bato.to/series/159888/toxin-official
> https://batotwo.com/series/159888/toxin-official
> https://readtoto.com/series/159888/toxin-official

For all of these, the result is the same. I have attached an image and the log. 

Thank you for taking a look at this bug,
![cant_download](https://github.com/user-attachments/assets/eabc399b-632d-49d6-be0e-d38dee49cff2)
[jvm_log_error_Toxin.txt](https://github.com/user-attachments/files/18220039/jvm_log_error_Toxin.txt)

**Comment by RedSquirrel87** [comment]
Hello, hope you are doing well and enjoying the winter holidays too :)
From what I can see, all the links you provided lead to a "are you human?" verification page with a recaptcha. The error you are encountering is indeed an HTTP 403, indicating that the program is unable to access the page due to that protection. Batoto probably activated this protection to safeguard their servers during the holiday season, possibly anticipating higher traffic than usual. Unfortunately, it is not possible to bypass such protections at the moment, so the only hope is that they will remove it soon

**Comment by RedSquirrel87** [comment]
Never mind, I just realized the error is occurring during the download of the chapters, not during the retrieval of the chapter list. I'll check further and see what is causing it 👍

**Comment by RedSquirrel87** [comment]
I checked further and unfortunately, even though the cause may differ, the issue remains the same. The chapter pages also have recaptcha protection, and it appears that we can't bypass it using cookies. I tried several times with the listed ones, but no luck. Since this did not happen before, I hope it's just an extra protection they've temporarily put in place. I will monitor the situation over the next few days to see if there is any update

**Comment by KassAndrose** [comment]
> I checked further and unfortunately, even though the cause may differ, the issue remains the same. The chapter pages also have recaptcha protection, and it appears that we can't bypass it using cookies. I tried several times with the listed ones, but no luck. Since this did not happen before, I hope it's just an extra protection they've temporarily put in place. I will monitor the situation over the next few days to see if there is any update

Thank you very much for investigating. 
That is a pity. Fingers crossed they remove it soon. ^^

**Comment by RedSquirrel87** [comment]
I searched for info on their social channels, it seems they are deprecating the main domain bato.to and there are server issues and redirects at the moment: https://www.reddit.com/r/Batoto/comments/1hj56gd/why_do_i_keep_getting_redirected_to_xbato/
This could be a good thing, maybe once they fix everything properly, they'll remove these protections. I've tested every single mirror listed [here](https://rentry.co/batoto), and they all have the protection active at the moment, none of them are exempt 😨

**Comment by RedSquirrel87** [comment]
Also, I found out that they seem to have suffered a DDoS attack yesterday: https://x.com/batoto_official/status/1870331084111847900
This explains better the new protection on all the domains, not exactly a great time for Batoto it seems 😅

**Comment by KassAndrose** [comment]
> Also, I found out that they seem to have suffered a DDoS attack yesterday: https://x.com/batoto_official/status/1870331084111847900 This explains better the new protection on all the domains, not exactly a great time for Batoto it seems 😅

Oh this makes so much sense. Thanks a lot for finding out all of this info. Fingers crossed they'll drop the safeguards at one point. 😊

I will close the bug then. Thank you.

**Comment by RedSquirrel87** [comment]
It's better to keep this issue open because otherwise it disappears from main view on GitHub, and then other users come and open many identical issues  xD

**Comment by KassAndrose** [comment]
> Since Batoto is a highly used source, it's better to keep this issue open because otherwise it disappears from main view on GitHub, and then other users come and open many identical issues xD

Oh that makes sense. Apologies. This was the first time I made a bug on Github. 😅 Thank you for reopening the bug.

**Comment by Enaella** [comment]
Hey :D well I am glad to see someone reported it. Noticed as well, that no matter what, unable to load chapter list. Noticed the message on bato that they are depreciating the domain bato.to.
thanks for all your work on fixing it :D and whishing you happy end of the years festivities.

**Comment by RedSquirrel87** [comment]
I've just tested it and it seems that Batoto and its mirror sites are working again now. Please check on your end as well and let me know if it works for you now 👍

**Comment by KassAndrose** [comment]
> I've just tested it and it seems that Batoto and its mirror sites are working again now. Please check on your end as well and let me know if it works for you now 👍

Yes, I can confirm, it works again! 🥳 Thank you.
