### ISSUE TITLE
Mangadex - can't open chapter list

### ISSUE THREAD

**Issue by AxelFaiz** [RedSquirrel87/manga-downloader#872]
Hello and greetings,

I tried to download from mangadex.org (e.g. https://mangadex.org/title/16dcfceb-4382-45f1-adb0-d57fc5ea0d06)
but after pasting the URL and open it, it shows this error:
![java_IApitgae7n](https://github.com/user-attachments/assets/0da12803-3cc0-4b47-a28f-ffde178f5c1f)
Obviously mangadex is working fine and I can read it fine in the browser.

I have tried with another URL from mangadex and it shows the same error. 
I've tried redownloading the Manga Downloader and open it in different directory, same ol' error. 
Tried updating my Java, still no luck. 
I first encountered this error sometimes in late November but due to my college assignments and final I never came around to report it, until now. Hopefully you can find the error and fix it.

Thank you so much :D
[jvm_log.txt](https://github.com/user-attachments/files/18266505/jvm_log.txt)

**Comment by RedSquirrel87** [comment]
Hello, I just tried the same URL and it doesn't seem to have any issue on my end:
![image](https://github.com/user-attachments/assets/844ad214-7cfe-4416-be5f-b6740b62149d)
The attached log also mentions a "connection refused" error, so there must be something on your side preventing the program from reaching the website. Are you using a VPN, proxy, or similar tools to access the internet? Do you have a firewall, antivirus, or other programs that might be blocking the program's connection? Can you test with another PC on the same network to see if it's an issue related to specific settings or programs on that particular PC? 

P.s.: also, be aware that Mangadex is blocked throught obscured DNS in some countries (such as Italy for example), so if you live in a similar country you need to set Google/Cloudflare DNS for your network connection 👍

**Comment by RedSquirrel87** [comment]
Oh, I also forgot to suggest that you can try the DNS bypass option that you can activate from the Extra -> Mangadex menu in the program, that might help too

**Comment by AxelFaiz** [comment]
So, I've tried the bypass DNS since I didn't use VPN or any other programs for blocking my internet connection. And, it works!!!
Thank you so much for the quick response and the fix.
