### ISSUE TITLE
agcsscanlation download not working

### ISSUE THREAD

**Issue by click1234bis** [RedSquirrel87/manga-downloader#875]
houseki no kuni
all chapters

[logAGCS.txt](https://github.com/user-attachments/files/18271214/logAGCS.txt)

**Comment by RedSquirrel87** [comment]
Thank you for reporting the issue, thanks to this I just noticed I forgot to remove the debug string in the log too 😅 
I will fix both things as soon as possible

**Comment by RedSquirrel87** [comment]
v70.1 released, it should fix this issue 👍
